global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'alerts.yml'

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: fraud_inference
    static_configs:
      - targets:
          - inference:8000
    metrics_path: '/metrics'

  - job_name: spark
    static_configs:
      - targets:
          - spark:4040

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
